print('>>> Seja bem vindo ao Python. Preciso de algumas informações sobre você.<<<')
print('')
nome = input('Qual é o seu nome? ')
idade = input('Qual é a sua idade? ')
peso = input('Qual é o seu peso? ')
print('Olá', nome +'. Registramos em nosso sistema a sua idade de', idade, 'anos e o seu peso de', peso, 'kgs. Tudo ok!')